"""initial schema

Revision ID: 151e4707ce5b
Revises: 
Create Date: 2026-03-31 13:04:56.391034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '151e4707ce5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_1m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('buy_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('sell_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volume_delta', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('quote_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('candles_5m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('buy_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('sell_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volume_delta', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('quote_volume', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('funding_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('funding_history',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('index_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('predicted_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('indicators_15m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema_9', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_21', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_200', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stochrsi_k', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stochrsi_d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd_line', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_line', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_hist', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_mid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_width', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('kc_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('kc_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_squeeze', sa.Boolean(), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('atr_pct_rank', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('supertrend', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('supertrend_dir', sa.SmallInteger(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_upper1', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_lower1', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_upper2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_lower2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('obv', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volume_delta', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('order_flow_imb', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ha_open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('funding_8h', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('funding_24h_cum', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('liq_volume_1h', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('indicators_5m',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema_9', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_21', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_50', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ema_200', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stochrsi_k', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('stochrsi_d', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('macd_line', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_line', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_signal', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('macd_fast_hist', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_mid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_width', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('kc_upper', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('kc_lower', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('bb_squeeze', sa.Boolean(), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('atr_pct_rank', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('supertrend', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('supertrend_dir', sa.SmallInteger(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_upper1', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_lower1', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_upper2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('vwap_dev_lower2', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('obv', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('volume_delta', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('order_flow_imb', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ha_open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('ha_close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('funding_8h', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('funding_24h_cum', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('liq_volume_1h', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('liquidations',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('value_usd', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'side', 'price')
    )
    op.create_table('raw_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('qty', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('trade_id', sa.String(length=40), nullable=False),
    sa.Column('is_liquidation', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp', 'trade_id')
    )
    op.create_table('strategy_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_combo', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('expectancy', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('best_regime', sa.String(length=20), nullable=True),
    sa.Column('worst_regime', sa.String(length=20), nullable=True),
    sa.Column('regime_funding', sa.String(length=10), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_combo', 'symbol', 'timeframe', 'regime_funding', name='uq_strategy_performance_combo')
    )
    op.create_table('trades_log',
    sa.Column('trade_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('leverage', sa.SmallInteger(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_size_usd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('pnl_usd', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('funding_paid_usd', sa.Numeric(precision=20, scale=4), server_default=sa.text('0'), nullable=True),
    sa.Column('win_loss', sa.Boolean(), nullable=True),
    sa.Column('strategy_combo', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('indicators_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('regime_volatility', sa.String(length=10), nullable=True),
    sa.Column('regime_funding', sa.String(length=10), nullable=True),
    sa.Column('regime_time_of_day', sa.String(length=15), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('is_backtest', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('trade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades_log')
    op.drop_table('strategy_performance')
    op.drop_table('raw_trades')
    op.drop_table('liquidations')
    op.drop_table('indicators_5m')
    op.drop_table('indicators_15m')
    op.drop_table('funding_history')
    op.drop_table('candles_5m')
    op.drop_table('candles_1m')
    # ### end Alembic commands ###
